### ISSUE TITLE
Add Support for Volumes (docker-compose.uffizzi.yml)

### ISSUE THREAD

**Issue by jpthurman** [UffizziCloud/uffizzi_app#126]
Add Uffizzi Compose support for volumes (short and long syntax) as define by Docker Compose here:

https://docs.docker.com/compose/compose-file/compose-file-v3/#volumes

**Comment by zipofar** [comment]
@jpthurman @axisofentropy @gadkins 

After long discussion was find 2 variants how we can implement this:
1. With addition extra config item

```
x-uffizzi-volumes:
  service: ${main_service}
  root_path: ${path_to_project_directory_into_container} 
```

For example use [this docker-compose](https://github.com/BretFisher/allhands22/blob/main/docker-compose.test.yml)
We should add:
```
x-uffizzi-volumes:
  service: allhands22
  root_path: /test 
```

`root_path: /test` - because Dockerfile has `WORKDIR /test`

2. With addition self hosted cloud storage https://min.io/product/kubernetes.
In this case we can upload files for volumes from `cli`

**Comment by axisofentropy** [comment]
> After long discussion was find 2 variants how we can implement this:

Thank you for composing this.

I don't think option 1 is what we're looking for.

Option 2 is good, but what's special about MinIO or other object storage? Couldn't the init container fetch the files from  `uffizzi_app` for example? We can set a small size limit for the files, which should probably be in something like a gzipped archive.

**Comment by axisofentropy** [comment]
We discussed this today and I think we're going to shrink the scope of this ticket to support only "empty" volumes. A use case for one of our customers: mounting an empty volume to `/var/lib/postgresql/data` so that they don't have to wait for the `postgres` container to reinitialize and re-seed when they push a new commit to their Pull Request.

I know we say it a lot, but we want this to behave much like `Kompose`. I tested it and it translated a `volume` in Docker Compose to a `PersistentVolumeClaim`. I applied this manifest to an EKS Cluster and It Just Worked; I didn't need to specify a `PersistentVolume`. I think this will make implementing empty volumes pretty straightforward.

Probably more specifications and protoyping coming soon, but let me know what you think!

(We will specify a new ticket soon for the other big use case of volumes that should have some files in them before preview containers start. I think Kubernetes' new "Init Containers" are the best way to implement this. Maybe they can even pull files directly from GitHub so we don't have to store them?)

**Comment by zipofar** [comment]
@axisofentropy 

> Maybe they can even pull files directly from GitHub so we don't have to store them?

But for opensource version we do not use github

**Comment by moklidia** [comment]
The lifecycle of the volume should be limited by the lifecycle of a namespace. If a pull request is closed - the volume is removed. If a commit is added to the branch - it should persist.

**Comment by moklidia** [comment]
A list of existing storage classes in qa:
<details>
<img width="962" alt="Снимок экрана 2022-06-08 в 11 20 24" src="https://user-images.githubusercontent.com/42300552/172581002-f64e3ac6-90f7-4708-a0e8-cad73f93d74b.png">
</details>

1) Create a namespace `volumes-test` `kubectl create namespace volumes-test`

2) Create a config map
<details>
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: volumes_test
  labels:
    app: postgres
data:
  POSTGRES_DB: postgresdb
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: test123
```
</details>
3) Create a volume claim (volume is created and bound automatically) and specify the `standard` storage name
<details>
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
  namespace: volumes-test
  labels:
    app: postgres
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50M
```
</details>
4) Create a service
<details>
```
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: volumes-test
  labels:
    app: postgres
spec:
  type: NodePort
  ports:
   - port: 5432
  selector:
   app: postgres
```
</details>
5) Create a deployment
<details>
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: volumes-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:10.1
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              subPath: pgdata
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pv-claim
```
</details>
6) Connect to the pod and start postgres `psql -h localhost -U admin --password -p 5432 postgresdb`
7) Create tables 
8) Restart deployment `kubectl rollout restart [deployment_name]`
9) Connect to the new pod: tables created in step 7 are available

**Comment by moklidia** [comment]
Next points to research:
- A pvc with the ReadWriteMany access mode hangs endlessly in pending status
- A PVC with a 50M request triggers a volume with 1Gi capacity

**Comment by gadkins** [comment]
If more than one container in the compose mounts the same volume, then only one container should have Read + Write permissions. All others should be Read-only. In this case, the you should be required to add the `ro` and `rw` MODE syntax (https://docs.docker.com/compose/compose-file/compose-file-v3/#short-syntax-3). If they user mounts the same volume to more than one container and does not specify `ro` and `rw`, then we should return an error that explains they must designate which container has `rw`.

**Comment by zipofar** [comment]
@gadkins @axisofentropy 

There is one more question about anonymous volume like:
```
volumes:
  - /var/log
```

Should we implement this type volumes in this issue?
Should this type volume  save state after update deployment?

**Comment by zipofar** [comment]
Add new `StorageClass`. Because was problem like [this](https://stackoverflow.com/questions/51946393/kubernetes-pod-warning-1-nodes-had-volume-node-affinity-conflict).

```
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
  name: uffizzi-standard
parameters:
  type: pd-standard
provisioner: kubernetes.io/gce-pd
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
```

**Comment by zipofar** [comment]
### HOW TO TEST: ###
* Create a preview
* Create some data
* Update preview
* Check that data is exists

We can use this compose file for check anonymous volumes:
```
services:
  web:
    image: zipofar/uffizzi_test_rails_simple:latest
    volumes:
      - /db

x-uffizzi:
  ingress:
    service: web
    port: 3000
```

We can use this compose file for check named volumes:
```
services:
  web:
    image: zipofar/uffizzi_test_rails_simple:latest
    volumes:
      - db_share:/db

volumes:
  db_share:

x-uffizzi:
  ingress:
    service: web
    port: 3000
```

**Comment by zipofar** [comment]
### TEST REMOVE UNUSED VOLUMES: ###
* create volume (for example)
```
services:
  web:
    image: zipofar/uffizzi_test_rails_simple:latest
    volumes:
      - share_db:/db

volumes:
  share_db:

x-uffizzi:
  ingress:
    service: web
    port: 3000
 ```
 * Add some data to DB
 * Change volume name
 ```
services:
  web:
    image: zipofar/uffizzi_test_rails_simple:latest
    volumes:
      - share_db_2:/db
volumes:
  share_db_2:

x-uffizzi:
  ingress:
    service: web
    port: 3000
 ```
 * Update preview
 * Return volume name back
 ```
services:
  web:
    image: zipofar/uffizzi_test_rails_simple:latest
    volumes:
      - share_db:/db

volumes:
  share_db:

x-uffizzi:
  ingress:
    service: web
    port: 3000
 ```
* Update preview
  
 Expected result: db should have init (empty) state

**Comment by zipofar** [comment]
Long syntax for named volume:
```
services:
 web:
   image: zipofar/uffizzi_test_rails_simple:latest
   volumes:
     - source: share_db
       target: /db
       read_only: true
       

volumes:
 share_db:

x-uffizzi:
 ingress:
   service: web
   port: 3000
```

**Comment by zipofar** [comment]
Read only for short syntax:
```
services:
 web:
   image: zipofar/uffizzi_test_rails_simple:latest
   volumes:
     - share_db_2:/db:ro
     
volumes:
 share_db_2:

x-uffizzi:
 ingress:
   service: web
   port: 3000
```

```
services:
 web:
   image: zipofar/uffizzi_test_rails_simple:latest
   volumes:
     - /db:ro
     
volumes:
 share_db_2:

x-uffizzi:
 ingress:
   service: web
   port: 3000
```
