### ISSUE TITLE
Support for GitHub module from platform

### ISSUE THREAD

**Issue by moklidia** [UffizziCloud/uffizzi_app#147]
Needs changes to be able to add dependency injection from the platform and use Github module in the platform.

**Comment by moklidia** [comment]
Needs to be released before releasing this feature:
https://github.com/UffizziCloud/uffizzi_app/issues/127

**Comment by moklidia** [comment]
For QA: 
This task shouldn't break the existing flow. Please test from CLI.
1) Add a compose file that specifies a build (like [this](https://github.com/moklidia/hello-world-1/blob/master/uffizzi-compose-hw.yml))
2) Should get an error that the 'build' option is not supported

**Comment by moklidia** [comment]
**Checked - OK**

1) Compose file
```
services:
  hello-world:
    build: 
      context: https://github.com/moklidia/hello-world-1
      dockerfile: Dockerfile
  nginx:
    image: nginx

x-uffizzi:
  ingress:
    service: hello-world
    port: 80
  continuous_previews:
    deploy_preview_when_pull_request_is_opened: true
    delete_preview_when_pull_request_is_closed: true
    delete_preview_when_image_tag_is_updated: true
    deploy_preview_when_image_tag_is_created: true
    share_to_github: true
```
2) Ran `bundle exec uffizzi project compose set --file 'test/compose_files/test_compose_success.yml'`

Result: `'build' option is not implemented`
<details>
<img width="977" alt="Снимок экрана 2022-06-03 в 13 42 32" src="https://user-images.githubusercontent.com/42300552/171847482-d9f816ee-4bee-45ed-b133-1cef3698df04.png">
</details>
