### ISSUE TITLE
BUG: [Not Fixed] Can't add new compose file if temporary compose file already exist

### ISSUE THREAD

**Issue by NealArw** [UffizziCloud/uffizzi_app#159]
1. Create a preview from the file with the command bundle exec uffizzi preview create uffizzi-compose-webhook-docker.yml
2. Try to add this (or another) file into Uffizzi with the command bundle exec uffizzi project compose set -f uffizzi-compose-webhook-docker.yml or by API

**Result:**

1. Error: `has already been taken`
2. Error message duplicates in CLI
![image](https://user-images.githubusercontent.com/10543986/164237926-e9ec4061-e544-4677-a606-60d31d7e047a.png)

**Comment by NealArw** [comment]
**TESTED - OK**

```
bash-5.1# bundle exec uffizzi project compose set -f test-compose/uffizzi-compose-volumes-docker.yml
compose file created
bash-5.1# bundle exec uffizzi project compose describe
services:
  volumes_test_app:
    image: zipofar/uffizzi_test_rails_simple:latest
    volumes:
      - /db:ro
    deploy:
      resources:
        limits:
          memory: 1000M

x-uffizzi-ingress:
  service: volumes_test_app
  port: 3000

x-uffizzi-continuous-preview:
  delete_preview_after: 1h
  tag_pattern: uffizzi_request_*
  delete_preview_when_image_tag_is_updated: true
  deploy_preview_when_image_tag_is_created: true
bash-5.1#
```

```
irb(main):002:0> UffizziCore::ComposeFile.all

#<UffizziCore::ComposeFile 
id: 27, 
source: "/gem/test-compose/uffizzi-compose-volumes-docker.y...", 
.... 
kind: "temporary">

#<UffizziCore::ComposeFile 
id: 28, 
source: "/gem/test-compose/uffizzi-compose-volumes-docker.y...", 
....
kind: "main">

```
