### ISSUE TITLE
Remap service hostsnames to real kubernetes hosts from docker-compose

### ISSUE THREAD

**Issue by waveywaves** [UffizziCloud/uffizzi_app#229]
**Tell us about your request**
When passing a docker-compose, where multiple services are dependent on each other, the hostname of the service which is being accessed is the same as the name of the service as follows.

```
services:
  db:
    image: postgres:11-alpine
    ...

  wiki:
    image: "${WIKI_IMAGE}"
    depends_on:
      - db
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: wikijsrocks
      DB_NAME: wiki
    ...

```
But when deploying this directly after adding the `x-uffizzi` ingress, the wiki container is not able to access the db. To make this work for uffizzi the user has to update the `DB_HOST` to `localhost`. This isn't very convenient because if I need to now use the docker-compose with just docker-compose, I need to either update `DB_HOST` again or use the `host` network mode in the docker compose. 

We should be able to use the uffizzi compose with docker-compose or with uffizzi without making any changes. The uffizzi_app should ideally be smart enough to create a dependency graph of these services and then rename the hostnames as necessary.  In this case, 
the `DB_HOST` will be updated to `localhost` _by uffizzi_app_ and _not by the user_. The plain docker-compose should just work as is.

**Which service(s) is this request for?**
Open Source and Cloud solution.

**Are you currently working around the issue?**
Update dependent hostnames to `localhost` manually.
