### ISSUE TITLE
Research the required healthcheck options and add validation

### ISSUE THREAD

**Issue by moklidia** [UffizziCloud/uffizzi_app#231]
If a user has a compose file with a healthcheck and does not have all the options, we get the `NoMethodError (undefined method `scan' for nil:NilClass)` error. We need to check the Kubernetes specifications and either require from users to input all the options (add validation) or change the logic so the error is not raised.

Available params for healthcheck:
```
{
  test
  interval
  timeout
  retries
  start_period
  disable
}
```

**Comment by zipofar** [comment]
https://sentry.io/organizations/uffizzi-cloud/issues/3495320049/?environment=production&project=1826818&query=is%3Aunresolved&statsPeriod=24h

**Comment by moklidia** [comment]
Please update documentation with this task too:
https://github.com/UffizziCloud/docs/issues/65

**Comment by zipofar** [comment]
If we do not define correct first param for `healthcheck: test`
`REQUIRED_START_COMMANDS = ['NONE', 'CMD', 'CMD-SHELL']`

```
services:
  nginx:
    image: zipofar/my_nginx_simple:latest
    healthcheck:
      test:
        - ls
      interval: 10s
      timeout: 5s
      start_period: 5s
      retries: 5

x-uffizzi:
  ingress:
    service: nginx
    port: 80
```


We get not human friendly error:

![Screenshot 2022-08-12 at 11 46 06](https://user-images.githubusercontent.com/22678201/184320305-0910d6b5-de32-4d36-b8ad-88a5ea8b0fb8.png)

**Comment by zipofar** [comment]
### HOW TO TEST: ###

Correct compose file example:
```
services:
  nginx:
    image: zipofar/my_nginx_simple:latest
    healthcheck:
      test:
        - CMD
      interval: 10s
      timeout: 5s
      start_period: 5s
      retries: 5

x-uffizzi:
  ingress:
    service: nginx
    port: 80
```
Params:
* test - If this is a list the first param should be one of: ['NONE', 'CMD', 'CMD-SHELL']
* interval, timeout, start_period - should have format: s | m | h | d (e.g. 5s or 5m...)
* retries - should be integer

Example errors:
![Screenshot 2022-08-15 at 10 56 13](https://user-images.githubusercontent.com/22678201/184598147-bce60b0c-7a2c-406d-be99-d584f338e551.png)

![Screenshot 2022-08-15 at 10 57 12](https://user-images.githubusercontent.com/22678201/184598178-15437ce1-30c2-4700-8b21-4b03457bc8ea.png)

![Screenshot 2022-08-15 at 10 56 42](https://user-images.githubusercontent.com/22678201/184598203-a3ed9c01-8bf1-486a-8b79-630435fd8d22.png)
