### ISSUE TITLE
Issues with deployment in failed state

### ISSUE THREAD

**Issue by NealArw** [UffizziCloud/uffizzi_app#236]

**Comment by JessikaCastellano** [comment]
To reproduce the error:
 

- Connect to `uffizzi_cli`
- Create preview from compose file `bundle exec uffizzi preview create compose.yml`

Example file: 

```
services:
  webhooks_test_app:
    image: uffizzitest/aaaa-webhooks-test-app:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

x-uffizzi-ingress:
  service: webhooks_test_app
  port: 80

x-uffizzi-continuous-preview:
  delete_preview_after: 1h
  delete_preview_when_image_tag_is_updated: true
  deploy_preview_when_image_tag_is_created: true
```

- Because the image in the `compose.yml` is invalid, this will return the message `Deployment failed `
