### ISSUE TITLE
Issues with deployment in failed state. CLI + app. Update.

### ISSUE THREAD

**Issue by NealArw** [UffizziCloud/uffizzi_app#243]
1. Connect uffizzitest docker hub account
2. Create preview from compose file `uffizzi preview create compose.yml`. The file contains a mistake: The image from compose file does not exist in the docker hub.
3. Wait until deployment failed with the error `Deployment failed`
4. Try to update failed deployment. Run `uffizzi preview update deployment-NUMBER test-compose/compose.ym`

**Result.** Deployment cannot be updated. 
Message:
``` 
# uffizzi preview update deployment-4 c.yml
Preview with ID deployment-4 was successfully updated.
Deployment Not Found
#
```
**Expected result**: We need to update the failed deployment and if it fails again - show `Deployment failed` message

--------------

**Compose example:**

```
services:
  webhooks_test_app:
    image: uffizzitest/aaaa-webhooks-test-app:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

x-uffizzi-ingress:
  service: webhooks_test_app
  port: 80

x-uffizzi-continuous-preview:
  delete_preview_after: 1h
  delete_preview_when_image_tag_is_updated: true
  deploy_preview_when_image_tag_is_created: true
```
