### ISSUE TITLE
Map UFFIZZI_URL value to other env vars using config

### ISSUE THREAD

**Issue by waveywaves** [UffizziCloud/uffizzi_app#251]
**Tell us about your request**
I would like to see the value associated to UFFIZZI_URL associated to other env vars mentioned in a config under `x-uffizzi` config under docker compose

**Which service(s) is this request for?**
kube controller, uffizzi_app

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
I need to map UFFIZZI_URL to other env vars at times when setting up user repos

**Describe the solution you'd like**
```
x-uffizzi:
  ingress:
    service: serving-em
    env-map:
    - "REDIRECT_URL"
    - "ENDPOINT"
```

**Are you currently working around the issue?**
Using docker-entrypoint.sh to export during runtime

**Additional context**
