### ISSUE TITLE
Issues with deployment in failed state. CLI + app. Output.

### ISSUE THREAD

**Issue by NealArw** [UffizziCloud/uffizzi_app#255]
1. Connect uffizzitest docker hub account
2. Create preview from compose file `uffizzi preview create compose.yml`. The file contains a mistake: The image from compose file does not exist in the docker hub. Run command with json output (e.g. `uffizzi preview create -o=json compose.yml`)
3. Wait until deployment failed with the error `Deployment failed`.

Result:
There is no json output with information about preview.

```
# uffizzi preview create -o=json compose.yml
[✔] Creating containers...
[✖] Deploying preview...
  [✖] aaaawebhooks-test-app
Deployment failed
```

Expected result example for completed preview:

```
# uffizzi preview create -o=json c1.yml
[✔] Creating containers...
[✔] Deploying preview...
  [✔] webhooks-test-app
{"id":"deployment-5","url":"https://deployment-NUM-test.com","containers_uri":"http://web:7000/projects/2/deployments/5/containers"}
```
--------------

**Compose example:**

```
services:
  webhooks_test_app:
    image: uffizzitest/aaaa-webhooks-test-app:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

x-uffizzi-ingress:
  service: webhooks_test_app
  port: 80

x-uffizzi-continuous-preview:
  delete_preview_after: 1h
  delete_preview_when_image_tag_is_updated: true
  deploy_preview_when_image_tag_is_created: true
```
