### ISSUE TITLE
Do not login to registry for pulling images from ttl.sh

### ISSUE THREAD

**Issue by waveywaves** [UffizziCloud/uffizzi_app#258]
**Tell us about your request**
When pulling from ttl.sh, there is no need to login. Uffizzi should be able to pull the image from the registry without requiring login.

**Which service(s) is this request for?**
Both

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
I am building a POC where you Uffizzi shouldn't need registry credentials for pulling images from registry. The registry of choice for this is ttl.sh. 

**Describe the solution you'd like**
Two proposed solutions
- Skip login when registry in use is ttl.sh
- Pull image first, if the pull fails then login and then try pulling

**Are you currently working around the issue?**
Nope.

**Additional context**
Using ttl.sh for building, pushing and pulling image in this github action 
https://github.com/waveywaves/backstage/actions/runs/3061623187/jobs/4941723075

**Comment by NealArw** [comment]
**TESTED - OK**

**Platform + Cli**

```
bash-5.1# bundle exec uffizzi preview create test-compose/uffizzi-compose-webhook-ttl.yml
Preview with ID deployment-1 was created.
[✔] Creating containers...
Done
[✔] Deploying preview...
  [✔] 7e64aa1d-6c2f-445d-afe4-16b599c831a1
Done
```


**If the user already has connected docker_registry integration, the user should disconnect it to use an anonymous registry (such as ttl.sh)**

**Comment by NealArw** [comment]
TESTED on prod - OK

Platform + Cli

```
services:
  webhooks_test_app:
    image: ttl.sh/7e64aa1d-6c2f-445d-afe4-16b599c831a1:2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

x-uffizzi-ingress:
  service: webhooks_test_app
  port: 80

x-uffizzi-continuous-preview:
  delete_preview_after: 1h
  delete_preview_when_image_tag_is_updated: true
  deploy_preview_when_image_tag_is_created: true
```

```
# uffizzi preview create c.yml
Preview with ID deployment-5881 was created.
[✔] Creating containers...
Done
[✔] Deploying preview...
  [✔] 7e64aa1d-6c2f-445d-afe4-16b599c831a1
Done
```
**If the user already has connected docker_registry integration, the user should disconnect it to use an anonymous registry (such as ttl.sh)**

**Comment by NealArw** [comment]
TESTED on prod - OK

Platform + Cli

```
services:
  webhooks_test_app:
    image: ttl.sh/7e64aa1d-6c2f-445d-afe4-16b599c831a1:2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

x-uffizzi-ingress:
  service: webhooks_test_app
  port: 80

x-uffizzi-continuous-preview:
  delete_preview_after: 1h
  delete_preview_when_image_tag_is_updated: true
  deploy_preview_when_image_tag_is_created: true
```

```
# uffizzi preview create c.yml
Preview with ID deployment-5881 was created.
[✔] Creating containers...
Done
[✔] Deploying preview...
  [✔] 7e64aa1d-6c2f-445d-afe4-16b599c831a1
Done
```
**If the user already has connected docker_registry integration, the user should disconnect it to use an anonymous registry (such as ttl.sh)**
