### ISSUE TITLE
Container Registry private images deploy

### ISSUE THREAD

**Issue by 7R41N33** [UffizziCloud/uffizzi_app#40]
```
Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  67s                default-scheduler  Successfully assigned deployment-9/app-deployment-9-5857c56dc5-t8btj to gke-uffizzi-client-sandbox-482f3ba5-ez9l
  Warning  Failed     45s                kubelet            Failed to pull image "limoha/devops-for-programmers-projectlvl-1:latest": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/limoha/devops-for-programmers-projectlvl-1:latest": failed to resolve reference "docker.io/limoha/devops-for-programmers-projectlvl-1:latest": pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
  Warning  Failed     45s                kubelet            Error: ErrImagePull
  Normal   BackOff    44s                kubelet            Back-off pulling image "limoha/devops-for-programmers-projectlvl-1:latest"
  Warning  Failed     44s                kubelet            Error: ImagePullBackOff
  Normal   Pulling    32s (x2 over 46s)  kubelet            Pulling image "limoha/devops-for-programmers-projectlvl-1:latest"
```

When the controller creates a new deployment the credential for a private registry hasn't been created yet. The pulling starts only after the second try. But the deployment in the rails app gets failed immediately after `Error: ImagePullBackOff`.

We need to re-run a deploy of containers when the app gets the `ImagePullBackOff` error and consider the retry count (because credentials can be invalid)

**Comment by NealArw** [comment]
```
services:
  webhooks-test-app:
    image: uffizzitest/test-private-repo:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

x-uffizzi-ingress:
  service: webhooks-test-app
  port: 80

x-uffizzi-continuous-preview:
  share_to_github: true
  delete_preview_after: 99h
  tag_pattern: uffizzi_request_*
  delete_preview_when_image_tag_is_updated: true
  deploy_preview_when_image_tag_is_created: true
  delete_preview_when_pull_request_is_closed: true
  deploy_preview_when_pull_request_is_opened: true    # i.e., value should be added in the Uffizzi Dashboard
```

```
bash-5.1# bundle exec uffizzi preview create -o=json test-compose/uffizzi-compose-webhook-docker-private.yml
[✔] Creating containers...
[✔] Deploying preview...
  [✔] test-private-repo
{"id":"deployment-16","url":"https://deployment-16.default.app.qa-gke.uffizzi.com"}
bash-5.1#
```
-----------------

```
services:
  webhooks-test-app:
    image: ghcr.io/nealarw/webhook-test-app:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

x-uffizzi-ingress:
  service: webhooks-test-app
  port: 80

x-uffizzi-continuous-preview:
  share_to_github: true
  delete_preview_after: 99h
  tag_pattern: uffizzi_request_*
  delete_preview_when_image_tag_is_updated: true
  deploy_preview_when_image_tag_is_created: true
  delete_preview_when_pull_request_is_closed: true
  deploy_preview_when_pull_request_is_opened: true    # i.e., value should be added in the Uffizzi Dashboard
```
<img width="873" alt="image" src="https://user-images.githubusercontent.com/89470900/162779754-be439a37-d6b4-490f-8092-1dd55c152aed.png">

```
bash-5.1# bundle exec uffizzi preview create -o=json test-compose/uffizzi-compose-webhook-ghcr.yml
[✔] Creating containers...
[✔] Deploying preview...
  [✔] webhook-test-app
{"id":"deployment-17","url":"https://deployment-17.default.app.qa-gke.uffizzi.com"}
```

**Comment by NealArw** [comment]
```
services:
  webhooks-test-app:
    image: gcr.io/uffizzi-pro-qa-gke/webhooks-test-app:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

x-uffizzi-ingress:
  service: webhooks-test-app
  port: 80

x-uffizzi-continuous-preview:
  share_to_github: true
  delete_preview_after: 99h
  tag_pattern: uffizzi_request_*
  delete_preview_when_image_tag_is_updated: true
  deploy_preview_when_image_tag_is_created: true
  delete_preview_when_pull_request_is_closed: true
  deploy_preview_when_pull_request_is_opened: true
```

```
bash-5.1# bundle exec uffizzi preview create -o=json test-compose/uffizzi-compose-webhook-google.yml
[✔] Creating containers...
[✔] Deploying preview...
  [✔] webhooks-test-app
{"id":"deployment-18","url":"https://deployment-18.default.app.qa-gke.uffizzi.com"}
bash-5.1#
```
-------------

```
services:
  webhooks-test-app:
    image: uffizziqa.azurecr.io/webhooks-test-app:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

x-uffizzi-ingress:
  service: webhooks-test-app
  port: 80

x-uffizzi-continuous-preview:
  share_to_github: true
  delete_preview_after: 99h
  tag_pattern: uffizzi_request_*
  delete_preview_when_image_tag_is_updated: true
  deploy_preview_when_image_tag_is_created: true
  delete_preview_when_pull_request_is_closed: true
  deploy_preview_when_pull_request_is_opened: true 
```

```
bash-5.1# bundle exec uffizzi preview create -o=json test-compose/uffizzi-compose-webhook-azure.yml
[✔] Creating containers...
[✔] Deploying preview...
  [✔] webhooks-test-app
{"id":"deployment-19","url":"https://deployment-19.default.app.qa-gke.uffizzi.com"}
```
