### ISSUE TITLE
Uffizzi CLI raise an error if a github repo is specified

### ISSUE THREAD

**Issue by 7R41N33** [UffizziCloud/uffizzi_app#41]
If someone is using an open-source installation of Uffizzi, then we should return a `Not implemented` error if the user passes a compose file that includes a GitHub build context, e.g.

```
services:
   web-app:
       build:
           context: https://github.com/example/web-app
```

**Comment by NealArw** [comment]
**TESTED - OK**

```
services:
  hello-world:
    build: 
      context: https://github.com/NealArw/hello-world-1
      dockerfile: /Dockerfile
      args:
        testarg: uffizzi_test

x-uffizzi:
  ingress:
    service: hello-world
    port: 80
    
  continuous_preview:
    share_to_github: true
    delete_preview_after: 101h
    delete_preview_when_image_tag_is_updated: true
    deploy_preview_when_image_tag_is_created: true
    delete_preview_when_pull_request_is_closed: true
    deploy_preview_when_pull_request_is_opened: true
```


```
bash-5.1# bundle exec uffizzi project compose set -f test-compose/uffizzi-compose-hw-local.yml
'build' option is not implemented
bash-5.1#
```
