### ISSUE TITLE
Fix config files job

### ISSUE THREAD

**Issue by 7R41N33** [UffizziCloud/uffizzi_app#53]
We need to add `UffizziCore::Controller::ApplyConfigFile::ConfigFileSerializer` serializer. For now, it is not defined but used in `controller_service`

**Comment by NealArw** [comment]
**TESTED - OK**


<details><summary>File: Click to expand</summary>

```
services:
  redis:
    image: redis:latest

  postgres:
    image: postgres:9.6
    secrets:
      - user
      - password

  nginx:
    image: nginx:latest
    configs:
      - source: my_config_2
        target: /etc/nginx/conf.d/default.conf

  worker:
    image: uffizzi/example-voting-app-worker:master
    deploy:
      resources:
        limits:
          memory: 250M

  vote:
    image: uffizzi/example-voting-app-vote:master

  result:
    image: uffizzi/example-voting-app-result:master

x-uffizzi-ingress:
  service: nginx
  port: 8080
  
x-uffizzi-continuous_preview:
  deploy_preview_when_pull_request_is_opened: true
  delete_preview_when_pull_request_is_closed: true
  delete_preview_after: 10h
  share_to_github: true
  deploy_preview_when_image_tag_is_created: true
  delete_preview_when_image_tag_is_updated: true
  
configs:
  my_config_2:
    file: ./config2/vote2.conf

secrets:
  user:
    external: true               # indicates value is external to this repository
    name: "POSTGRES_USER"  
  password:
    external: true               # indicates value is external to this repository
    name: "POSTGRES_PASSWORD"  
```
</details>

<details><summary>Result: Click to expand</summary>

```
bash-5.1# bundle exec uffizzi preview create -o=json test-compose/uffizzi-vote-app-docker.yml
[✔] Creating containers...
[✔] Deploying preview...
  [✔] postgres
  [✔] redis
  [✔] example-voting-app-result
  [✔] example-voting-app-vote
  [✔] example-voting-app-worker
  [✔] nginx
{"id":"deployment-8","url":"https://deployment-8.default.app.qa-gke.uffizzi.com"}
```

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/89470900/163193036-39e0a5bd-345e-4936-9074-9dd857677c38.png">

</details>
