### ISSUE TITLE
Uffizzi Platform Add Github Container Registry Integration

### ISSUE THREAD

**Issue by 7R41N33** [UffizziCloud/uffizzi_app#59]
We need support for GHCR in the same way we have support for GCR, ACR etc
Compose will need to support pulling images from GHCR - same integration functionality as the other registries

**Comment by NealArw** [comment]
**1.** Can't add file with GHCR repo:

**Example of the file:**

```
services:
  webhooks-test-app:
    image: ghcr.io/nealarw/webhook-test-app:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

x-uffizzi-ingress:
  service: webhooks-test-app
  port: 80

x-uffizzi-continuous-preview:
  share_to_github: true
  delete_preview_after: 99h
  tag_pattern: uffizzi_request_*
  delete_preview_when_image_tag_is_updated: true
  deploy_preview_when_image_tag_is_created: true
  delete_preview_when_pull_request_is_closed: true
  deploy_preview_when_pull_request_is_opened: true
```
**Result:**
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/89470900/164506914-a08c02ec-e901-418e-a9d6-f3ee8c62bd3f.png">

**2.** What type of credentials should I connect to deploy from GHCR?

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/89470900/164507331-62befacc-d5a0-442b-a0f2-47b1494a0dd4.png">
