### ISSUE TITLE
Bug: Time-out for status in the Platform UI.

### ISSUE THREAD

**Issue by jpthurman** [UffizziCloud/uffizzi_app#61]
Customer #62

Service shows "Red" in UI but is actually a live container

This service does a db schema migration and seeds the database.  I think uffizzi_app is timing out too soon and showing a red status when this container needs more time to complete it's tasks.  Could also be related to the type of service and how it responds to our healthchecks 

@axisofentropy we may need to consult with customer to get more details

**Comment by axisofentropy** [comment]
Probably happens more often when the Cluster is busy auto scaling.

**Comment by moklidia** [comment]
The following settings make it fail:

```
  service_checks:
    ip_ping_timeout: 1800s
    availability_timeout: 1800s
    await_status_timeout: 1800s
    await_rolling_update_timeout: 900s
    step_awaiting_rolling_update: 6s
    per_address_attempts: 180
    per_address_timeout: 1800s
```
