### ISSUE TITLE
BUG: Specifying branch in compose results in error message

### ISSUE THREAD

**Issue by 7R41N33** [UffizziCloud/uffizzi_app#71]
When adding this compose file, Uffizzi displays an error that says that the repo doesn't exist, even though it does. I'm not sure if it matters, but I've added the compose file from my personal GitHub account (`gadkins`), but the `results` services comes from the `UffizziCloud` GitHub account.  

https://github.com/gadkins/example-voting-worker/blob/main/docker-compose.uffizzi.yml  

When the `#main` branch is specified, Uffizzi displays the above error message.  
```
  result:
    build:
      context: https://github.com/UffizziCloud/example-voting-result#main
      dockerfile: Dockerfile
```

However, when I remove the `#main` branch, Uffizzi recognizes this file as valid compose.  

```
  result:
    build:
      context: https://github.com/UffizziCloud/example-voting-result
      dockerfile: Dockerfile
```

![image](https://user-images.githubusercontent.com/10543986/164229683-4c0c1a6d-2ab8-4950-9505-68d030ec547b.png)
