### ISSUE TITLE
BUG: Parsing compose file error: Invalid config option with number at the beginning of the string

### ISSUE THREAD

**Issue by 7R41N33** [UffizziCloud/uffizzi_app#77]

**Comment by NealArw** [comment]
**Was not fixed:**

Platform:
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/89470900/174600746-f7106fb6-738b-4817-97d8-92404cbe6fa1.png">

File:
```
services:
  1-hello-world:
    build: 
      context: https://github.com/NealArw/hello-world-1
      dockerfile: /Dockerfile
      args:
        testarg: uffizzi_test

x-uffizzi:
  ingress:
    service: 1-hello-world
    port: 80
    
  continuous_preview:
    share_to_github: true
    delete_preview_after: 1h
    delete_preview_when_image_tag_is_updated: true
    deploy_preview_when_image_tag_is_created: true
    delete_preview_when_pull_request_is_closed: true
    deploy_preview_when_pull_request_is_opened: true
```

----------
CLI:
```
bash-5.1# bundle exec uffizzi project compose set -f test-compose/uffizzi-compose-webhook-docker.yml
Invalid config option '1-webhooks_test_app' - only [a-zA-Z0-9\._\-] characters are allowed
bash-5.1#
```

File:
```
services:
  1-webhooks_test_app:
    image: uffizzitest/webhooks-test-app:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

x-uffizzi-ingress:
  service: 1-webhooks_test_app
  port: 80

x-uffizzi-continuous-preview:
  share_to_github: true
  delete_preview_after: 1h
  tag_pattern: uffizzi_request_*
  delete_preview_when_image_tag_is_updated: true
  deploy_preview_when_image_tag_is_created: true
  delete_preview_when_pull_request_is_closed: true
  deploy_preview_when_pull_request_is_opened: true
```

**Comment by NealArw** [comment]
APP - **TESTED on prod - OK**

```
# uffizzi project compose set -f compose.yml
compose file created
# uffizzi project compose describe
services:
  1-webhooks_test_app:
    image: uffizzitest/webhooks-test-app:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

x-uffizzi-ingress:
  service: 1-webhooks_test_app
  port: 80

x-uffizzi-continuous-preview:
  share_to_github: true
  delete_preview_after: 1h
  tag_pattern: uffizzi_request_*
  delete_preview_when_image_tag_is_updated: true
  deploy_preview_when_image_tag_is_created: true
  delete_preview_when_pull_request_is_closed: true
  deploy_preview_when_pull_request_is_opened: true
#
```
